services:
  - type: web
    name: classmate-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCNskuNEMATDRNbZjnDaCoV1G5I9oSlzXE
      - key: MONGO_URI
        value: mongodb+srv://evvganesh1:Ganesh714714@classmate.optdtwr.mongodb.net/?retryWrites=true&w=majority&appName=Classmate&tls=true
      - key: SECRET_KEY
        value: your-secret-key-for-local-development
